### ISSUE TITLE
Download snapshot in upgrader script

### ISSUE THREAD

**Issue by yutongp** [iotexproject/iotex-bootstrap#142]
If there is no dB files under IOTEX_HOME/data , ask user if they want to download correspondence snapshot. If user  answers YES, then download, unzip and put in data folder for them.

Tar file to download:
If user choose to turn on gateway on mainnet:
https://t.iotex.me/mainnet-data-with-idx-latest
If user choose to turn off gateway on mainnet:
https://t.iotex.me/mainnet-data-latest
If user choose to turn on gateway on testnet:
https://t.iotex.me/testnet-data-with-idx-latest
If user choose to turn off gateway on testnet:
https://t.iotex.me/testnet-data-latest

**Comment by raullenchai** [comment]
Done
