### ISSUE TITLE
Unable to start node without docker

### ISSUE THREAD

**Issue by oggy95** [iotexproject/iotex-bootstrap#149]
Hello.
Trying to setup node and connect to mainnet without docker via README of this repository.
But when I start the node, I've got an error:

> sudo ./iotex-server -config-path=/data/iotex-var/etc/config.yaml -genesis-path=/data/iotex-var/etc/genesis.yaml -plugin=gateway
> 2020/06/16 06:42:22 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
> {"level":"info","ts":1592289742.4042342,"caller":"server/main.go:65","msg":"Config in use: {Plugins:map[0:<nil>] Network:{Host:0.0.0.0 Port:4689 ExternalHost:\*.\*.\*.\* ExternalPort:4689 BootstrapNodes:[/dns4/bootnode-0.mainnet.iotex.one/tcp/4689/p2p/12D3KooWPfQDF8ASjd4r7jS9e7F1wn6zod7Mf4ERr8etoY6ctQp5 /dns4/bootnode-1.mainnet.iotex.one/tcp/4689/p2p/12D3KooWN4TQ1CWRA7yvJdQCdti1qARLXXu2UEHJfycn3XbnAnRh /dns4/bootnode-2.mainnet.iotex.one/tcp/4689/p2p/12D3KooWSiktocuUke16bPoW9zrLawEBaEc1UriaPRwm82xbr2BQ /dns4/bootnode-3.mainnet.iotex.one/tcp/4689/p2p/12D3KooWEsmwaorbZX3HRCnhkMPjMAHzwu3om1pdGrtVm2QaM35n] MasterKey:ee19d7a9dd4f9bf5e7ce6cdd170c940d4f5fdf99f5c5aefd76cd0fd10c3d028f RelayType: RateLimit:{GlobalUnicastAvg:300 GlobalUnicastBurst:500 PeerAvg:300 PeerBurst:500} EnableRateLimit:true PrivateNetworkPSK:} Chain:{ChainDBPath:/root/iotex-var/data/chain.db TrieDBPath:/root/iotex-var/data/trie.db IndexDBPath:/var/data/index.db CandidateIndexDBPath:/var/data/candidate.index.db ID:1 Address: ProducerPrivKey: SignatureScheme:[secp256k1] EmptyGenesis:false GravityChainDB:{DbPath:/root/iotex-var/data/poll.db NumRetries:8 MaxCacheSize:0 RDS:{AwsRDSEndpoint: AwsRDSPort:0 AwsRDSUser: AwsPass: AwsDBName:} SQLITE3:{SQLite3File:} SplitDBSizeMB:0 SplitDBHeight:0 HistoryStateRetention:0} Committee:{NumOfRetries:20 GravityChainAPIs:[https://mainnet.infura.io/v3/63720cd30b674dafa601606ee4c12ca5] GravityChainHeightInterval:0 GravityChainStartHeight:0 GravityChainCeilingHeight:0 RegisterContractAddress: StakingContractAddress: PaginationSize:255 VoteThreshold: ScoreThreshold: SelfStakingThreshold: CacheSize:1000 NumOfFetchInParallel:0 SkipManifiedCandidate:false GravityChainBatchSize:0} EnableTrielessStateDB:true EnableArchiveMode:false EnableAsyncIndexWrite:true EnableSystemLogIndexer:false EnableStakingProtocol:true CompressBlock:false AllowedBlockGasResidue:10000 MaxCacheSize:1000 PollInitialCandidatesInterval:10s WorkingSetCacheSize:20} ActPool:{MaxNumActsPerPool:32000 MaxGasLimitPerPool:320000000 MaxNumActsPerAcct:2000 ActionExpiry:10m0s MinGasPriceStr:1000000000000 BlackList:[]} Consensus:{Scheme:ROLLDPOS RollDPoS:{FSM:{EventChanSize:10000 UnmatchedEventTTL:3s UnmatchedEventInterval:100ms AcceptBlockTTL:4s AcceptProposalEndorsementTTL:2s AcceptLockEndorsementTTL:2s CommitTTL:2s} ToleratedOvertime:2s Delay:10s ConsensusDBPath:/var/data/consensus.db}} BlockSync:{Interval:10s BufferSize:400 IntervalSize:20 MaxRepeat:3 RepeatDecayStep:3} Dispatcher:{EventChanSize:10000} API:{UseRDS:false Port:14014 TpsWindow:10 GasStation:{SuggestBlockWindow:20 DefaultGas:1000000000000 Percentile:60} RangeQueryLimit:1000} System:{Active:true HeartbeatInterval:10s HTTPAdminPort:9009 HTTPStatsPort:8080 StartSubChainInterval:10s SystemLogDBPath:/var/data/systemlog.db} DB:{DbPath: NumRetries:3 MaxCacheSize:64 RDS:{AwsRDSEndpoint: AwsRDSPort:0 AwsRDSUser: AwsPass: AwsDBName:} SQLITE3:{SQLite3File:./explorer.db} SplitDBSizeMB:0 SplitDBHeight:900000 HistoryStateRetention:2000} Log:{Zap:0xc0000cd100 StderrRedirectFile:0xc000274670 RedirectStdLog:true} SubLogs:map[global:{Zap:0xc0000cd100 StderrRedirectFile:0xc000274670 RedirectStdLog:true}] Genesis:{Blockchain:{Timestamp:1553558500 BlockGasLimit:20000000 ActionGasLimit:5000000 BlockInterval:10s NumSubEpochs:15 DardanellesNumSubEpochs:30 NumDelegates:24 NumCandidateDelegates:36 TimeBasedRotation:true PacificBlockHeight:432001 AleutianBlockHeight:864001 BeringBlockHeight:1512001 CookBlockHeight:1641601 DardanellesBlockHeight:1816201 DaytonaBlockHeight:3238921 EasterBlockHeight:4478761 FbkMigrationBlockHeight:5157001 FairbankBlockHeight:5165641} Account:{InitBalanceMap:map[io10a298zmzvrt4guq79a9f4x7qedj59y7ery84he:100000000000000000000000000 io13sj9mzpewn25ymheukte4v39hvjdtrfp00mlyv:100000000000000000000000000 io14gnqxf9dpkn05g337rl7eyt2nxasphf5m6n0rd:100000000000000000000000000 io158hyzrmf4a8xll7gfc8xnwlv70jgp44tzy5nvd:100000000000000000000000000 io15flratm0nhh5xpxz2lznrrpmnwteyd86hxdtj0:100000000000000000000000000 io19d0p3ah4g8ww9d7kcxfq87yxe7fnr8rpth5shj:100000000000000000000000000 io19kshh892255x4h5ularvr3q3al2v8cgl80fqrt:100000000000000000000000000 io1cdqx6p5rquudxuewflfndpcl0l8t5aezen9slr:100000000000000000000000000 io1cl6rl2ev5dfa988qmgzg2x4hfazmp9vn2g66ng:100000000000000000000000000 io1ed52svvdun2qv8sf2m0xnynuxfaulv6jlww7ur:100000000000000000000000000 io1eq4ehs6xx6zj9gcsax7h3qydwlxut9xcfcjras:100000000000000000000000000 io1fxzh50pa6qc6x5cprgmgw4qrp5vw97zk5pxt3q:100000000000000000000000000 io1hh97f273nhxcq8ajzcpujtt7p9pqyndfmavn9r:100000000000000000000000000 io1jh0ekmccywfkmj7e8qsuzsupnlk3w5337hjjg2:100000000000000000000000000 io1juvx5g063eu4ts832nukp4vgcwk2gnc5cu9ayd:100000000000000000000000000 io1k9y4a9juk45zaqwvjmhtz6yjc68twqds4qcvzv:100000000000000000000000000 io1l3wc0smczyay8xq747e2hw63mzg3ctp6uf8wsg:100000000000000000000000000 io1llupp3n8q5x8usnr5w08j6hc6hn55x64l46rr7:100000000000000000000000000 io1ns7y0pxmklk8ceattty6n7makpw76u770u5avy:100000000000000000000000000 io1ph0u2psnd7muq5xv9623rmxdsxc4uapxhzpg02:100000000000000000000000000 io1q4tdrahguffdu4e9j9aj4f38p2nee0r9vlhx7s:100000000000000000000000000 io1skmqp33qme8knyw0fzgt9takwrc2nvz4sevk5c:100000000000000000000000000 io1uqhmnttmv0pg8prugxxn7d8ex9angrvfjfthxa:9800000000000000000000000000 io1v3gkc49d5vwtdfdka2ekjl3h468egun8e43r7z:100000000000000000000000000 io1vrl48nsdm8jaujccd9cx4ve23cskr0ys6urx92:100000000000000000000000000 io1xuavja5dwde8pvy4yms06yyncad4yavghjhwra:100000000000000000000000000 io1yhvu38epz5vmkjaclp45a7t08r27slmcc0zjzh:100000000000000000000000000 io1znka733xefxjjw2wqddegplwtefun0mfdmz7dw:100000000000000000000000000]} Poll:{PollMode:nativeMix EnableGravityChainVoting:true GravityChainStartHeight:7614500 GravityChainCeilingHeight:10199000 GravityChainHeightInterval:100 RegisterContractAddress:0x95724986563028deb58f15c5fac19fa09304f32d StakingContractAddress:0x87c9dbff0016af23f5b1ab9b8e072124ab729193 NativeStakingContractAddress:io1xpq62aw85uqzrccg9y5hnryv8ld2nkpycc3gza NativeStakingContractCode: ConsortiumCommitteeContractCode: VoteThreshold:100000000000000000000 ScoreThreshold:2000000000000000000000000 SelfStakingThreshold:1200000000000000000000000 Delegates:[] ProbationEpochPeriod:6 ProbationIntensityRate:90 UnproductiveDelegateMaxCacheSize:20} Rewarding:{InitBalanceStr:200000000000000000000000000 BlockRewardStr:16000000000000000000 DardanellesBlockRewardStr:8000000000000000000 EpochRewardStr:12500000000000000000000 AleutianEpochRewardStr:18750000000000000000000 NumDelegatesForEpochReward:100 ExemptAddrStrsFromEpochReward:[io15fqav3tugm96ge7anckx0k4gukz5m4mqf0jpv3 io1x9kjkr0qv2fa7j4t2as8lrj223xxsqt4tl7xp7 io1ar5l5s268rtgzshltnqv88mua06ucm58dx678y io1xsx5n94kg2zv64r7tm8vyz9mh86amfak9ka9xx io1vtm2zgn830pn6auc2cvnchgwdaefa9gr4z0s86 io159fv8mu9d5djk8u2t0flgw4yqmt6fg98uqjka8 io1c3r4th3zrk4uhv83a9gr4gvn3y6pzaj6mc84ea io14vmhs9c75r2ptxdaqrtk0dz7skct30pxmt69d9 io1gf08snppu2a2wfd50pjas2j6q2kcxjzqph3pep io1u5ff879gg2dw9vfpxr2tsmuaz07e2rea6gvl7s io1du4eq4f88n4wyc026l3gamjwetlgsg4jz7j884 io12yxdwewry70gr9fs6fphyfaky9c7gurmzk8f4f io1lx53nfgq2dnzrz5ecz2ecs7vvl6qll0mkn970w io1u5xy0ecnrjrdkzyctfqh37lgr5pcfzphgqrdwt io1aj8arp07xw6s9rgh42af5xf98csyuehnnwlk52 io18gdmv5g0xhkuj2cdyvp8076uwhl7h3gesmzh8u io1td5fvamm3qf22r5h93gay6ggqdh9z0edeqx63u io1qs785af9k9xf3xgd6vut7um9zcthtrvsn2xap2 io127ftn4ry6wgxdrw4hcd6gdwqlq70ujk98dvtw5 io1wv5m0xyermvr2n0wjx2cjsqwyk863drdl5qfyn io1v0q5g2f8z6l3v25krl677chdx7g5pwt9kvqfpc io1xsdegzr2hdj5sv5ad4nr0yfgpsd98e40u6svem io1fks575kklxafq4fwjccmz5d3pmq5ynxk5h6h0v io15npzu93ug8r3zdeysppnyrcdu2xssz0lcam9l9 io1gh7xfrsnj6p5uqgjpk9xq6jg9na28aewgp7a9v io1nyjs526mnqcsx4twa7nptkg08eclsw5c2dywp4 io1jafqlvntcxgyp6e0uxctt3tljzc3vyv5hg4ukh io1z7mjef7w528nasnsafan0rp6yuvkvq405l6r8j io1cup9k8hl8fp40vrj29ex8djc346780dk223end io1scs89jur7qklzh5vfrmha3c40u8yajjx6kvzg9 io10kyvvzu08pjeylymq4umknjal25ea3ptfknrpf io18mvepyxkcd5jkyplfqn27ydkpsendrey3xe2l8 io1nz40npqa3yvek4zdasmqaetl2j4h6urejfkera io1m7p9yrejngxyvxhvn7p9g9uwlvd7uuamg8wcjd io1cwwm08dwv9phh3wt5vsdhu9gcypw9q2sc7pl9s io14aj46jjmtt83vts9syhrs9st80czumg40cjasl] FoundationBonusStr:80000000000000000000 NumDelegatesForFoundationBonus:36 FoundationBonusLastEpoch:8760 FoundationBonusP2StartEpoch:9698 FoundationBonusP2EndEpoch:18458 ProductivityThreshold:85} Staking:{VoteWeightCalConsts:{DurationLg:1.2 AutoStake:1 SelfStake:1.06} RegistrationConsts:{Fee:100000000000000000000 MinSelfStake:1200000000000000000000000} WithdrawWaitingPeriod:72h0m0s MinStakeAmount:100000000000000000000 BootstrapCandidates:[]}}}","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689"}
> {"level":"info","ts":1592289742.407197,"caller":"committee/committee.go:149","msg":"Carrier created","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689","registerContractAddress":"0x95724986563028deb58f15c5fac19fa09304f32d","stakingContractAddress":"0x87c9dbff0016af23f5b1ab9b8e072124ab729193"}
> {"level":"info","ts":1592289742.4089408,"caller":"blockchain/blockchain.go:430","msg":"Add a subscriber.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689"}
> {"level":"info","ts":1592289742.4101293,"caller":"blockchain/blockchain.go:430","msg":"Add a subscriber.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689"}
> {"level":"info","ts":1592289742.4148414,"caller":"poll/nativestaking.go:176","msg":"Set native staking contract address = io1xpq62aw85uqzrccg9y5hnryv8ld2nkpycc3gza","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689"}
> {"level":"info","ts":1592289742.421036,"caller":"go-p2p@v0.2.12/p2p.go:359","msg":"P2p host started.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689","address":["/ip4/127.0.0.1/tcp/4689/p2p/12D3KooWMW3fVB8NnfYcCcfHcn2aGDPKWGji1wR8jVn7cTKL9UJ8","/ip4/\*.\*.\*.\*/tcp/4689/p2p/12D3KooWMW3fVB8NnfYcCcfHcn2aGDPKWGji1wR8jVn7cTKL9UJ8","/ip4/\*.\*.\*.\*/tcp/4689/p2p/12D3KooWMW3fVB8NnfYcCcfHcn2aGDPKWGji1wR8jVn7cTKL9UJ8"],"secureIO":true,"gossip":true}
> {"level":"info","ts":1592289743.42017,"caller":"p2p/agent.go:256","msg":"Connected bootstrap node.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689","address":"/dns4/bootnode-1.mainnet.iotex.one/tcp/4689/p2p/12D3KooWN4TQ1CWRA7yvJdQCdti1qARLXXu2UEHJfycn3XbnAnRh"}
> {"level":"info","ts":1592289743.4209867,"caller":"p2p/agent.go:256","msg":"Connected bootstrap node.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689","address":"/dns4/bootnode-2.mainnet.iotex.one/tcp/4689/p2p/12D3KooWSiktocuUke16bPoW9zrLawEBaEc1UriaPRwm82xbr2BQ"}
> {"level":"info","ts":1592289743.442204,"caller":"p2p/agent.go:256","msg":"Connected bootstrap node.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689","address":"/dns4/bootnode-0.mainnet.iotex.one/tcp/4689/p2p/12D3KooWPfQDF8ASjd4r7jS9e7F1wn6zod7Mf4ERr8etoY6ctQp5"}
> {"level":"fatal","ts":1592289743.4426446,"caller":"itx/server.go:174","msg":"Failed to start server.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689","error":"error when starting blockchain: error when starting election committee: unable to open database file","errorVerbose":"unable to open database file\nerror when starting election committee\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/root/iotex-core/chainservice/chainservice.go:404\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:173\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/.go/src/runtime/proc.go:203\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:98\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:173\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/.go/src/runtime/proc.go:203\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357"}

where \*.\*.\*.\* - my external ip.

**Comment by raullenchai** [comment]
Thanks for reporting. Team is looking into this one

**Comment by dustinxie** [comment]
@oggy95  find this line in config.yaml
`# externalHost: SET YOUR EXTERNAL IP HERE (e.g., 12.34.56.78)`
you will need to uncomment set a valid IP that has WAN access, for example
`externalHost: 75.121.32.49`

**Comment by oggy95** [comment]
In config.yaml I set external IP of server. Its valid, I don't expose it in log here.

**Comment by dustinxie** [comment]
could you upload your config.yaml, so we can take a look?

**Comment by yutongp** [comment]
can you verify if you have downloaded the latest snapshot with index and put all db files in snapshot  directly under the location you point in your config? (`/data/iotex-var/data`)

**Comment by dustinxie** [comment]
to add a little bit clarification, log shows the error:

```
{"level":"fatal","ts":1592289743.4426446,"caller":"itx/server.go:174","msg":"Failed to start server.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689","error":"error when starting blockchain: error when starting election committee: unable to open database file","errorVerbose":"unable to open database file\nerror when starting election committee\ngithub.com/iotexproject/iotex-core/chainservice. 
```

that means it cannot open file `/data/iotex-var/data/poll.db`

**Comment by oggy95** [comment]
![image](https://user-images.githubusercontent.com/14967777/84937559-a118a380-b0e4-11ea-8958-7393e7a6d4eb.png)
reload snapshot, get error

`{"level":"fatal","ts":1592419811.0192494,"caller":"itx/server.go:174","msg":"Failed to start server.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689","error":"error when starting blockchain: error when starting candidate indexer: open /var/data/candidate.index.db: no such file or directory: DB I/O operation error","errorVerbose":"DB I/O operation error\ngithub.com/iotexproject/iotex-core/db.init\n\t/root/iotex-core/db/kvstore_impl.go:25\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5222\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5217\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5217\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5217\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5217\nruntime.main\n\t/root/.go/src/runtime/proc.go:190\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357\nopen /var/data/candidate.index.db: no such file or directory\ngithub.com/iotexproject/iotex-core/db.(*boltDB).Start\n\t/root/iotex-core/db/db_bolt.go:43\ngithub.com/iotexproject/iotex-core/action/protocol/poll.(*CandidateIndexer).Start\n\t/root/iotex-core/action/protocol/poll/candidateindexer.go:51\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/root/iotex-core/chainservice/chainservice.go:408\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:173\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/.go/src/runtime/proc.go:203\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357\nerror when starting candidate indexer\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/root/iotex-core/chainservice/chainservice.go:409\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:173\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/.go/src/runtime/proc.go:203\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:98\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:173\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/.go/src/runtime/proc.go:203\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357"}`

now trying to download and unpack snapshot with index file

**Comment by oggy95** [comment]
`{"level":"fatal","ts":1592421760.3183773,"caller":"itx/server.go:174","msg":"Failed to start server.","ioAddr":"io1zda5z84lyupaycxtfp87y96dy0d36frgx4pv2g","networkAddr":"0.0.0.0:4689","error":"error when starting blockchain: error when starting candidate indexer: open /var/data/candidate.index.db: no such file or directory: DB I/O operation error","errorVerbose":"DB I/O operation error\ngithub.com/iotexproject/iotex-core/db.init\n\t/root/iotex-core/db/kvstore_impl.go:25\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5222\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5217\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5217\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5217\nruntime.doInit\n\t/root/.go/src/runtime/proc.go:5217\nruntime.main\n\t/root/.go/src/runtime/proc.go:190\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357\nopen /var/data/candidate.index.db: no such file or directory\ngithub.com/iotexproject/iotex-core/db.(*boltDB).Start\n\t/root/iotex-core/db/db_bolt.go:43\ngithub.com/iotexproject/iotex-core/action/protocol/poll.(*CandidateIndexer).Start\n\t/root/iotex-core/action/protocol/poll/candidateindexer.go:51\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/root/iotex-core/chainservice/chainservice.go:408\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:173\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/.go/src/runtime/proc.go:203\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357\nerror when starting candidate indexer\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/root/iotex-core/chainservice/chainservice.go:409\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:97\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:173\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/.go/src/runtime/proc.go:203\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/root/iotex-core/server/itx/server.go:98\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/root/iotex-core/server/itx/server.go:173\nmain.main\n\t/root/iotex-core/server/main.go:101\nruntime.main\n\t/root/.go/src/runtime/proc.go:203\nruntime.goexit\n\t/root/.go/src/runtime/asm_amd64.s:1357"}`

with index snapshot

due this string: open /var/data/candidate.index.db: no such file or directory:

somewhere don't changed path to file, but in config.yaml I set right path

**Comment by yutongp** [comment]
can you use the latest config: https://github.com/iotexproject/iotex-bootstrap/blob/master/config_mainnet.yaml
and set all db path to where you put them?

**Comment by oggy95** [comment]
@yutongp yes, worked

then need to update links in tutorial in readme
