### ISSUE TITLE
Cannot docker pull v1.1.1

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-bootstrap#162]
The docker image cannot be pulled. Also Docker HUB shows "0 bytes" for the size of the image:

<img width="781" alt="Schermata 2020-08-23 alle 20 10 36" src="https://user-images.githubusercontent.com/11096047/90985660-b0511d00-e57d-11ea-9854-e89670916a17.png">

```
» docker pull iotex/iotex-core:v1.1.1

v1.1.1: Pulling from iotex/iotex-core
df20fa9351a1: Already exists 
73249b6d84aa: Already exists 
4766d37a6dd4: Already exists 
4a7266942057: Pulling fs layer 
7f45140ce81b: Pulling fs layer 
be4e563096cd: Pulling fs layer 
c8816247370e: Waiting 
error pulling image configuration: unknown blob
```

**Comment by yutongp** [comment]
something wrong with dockerhub auto build. 
not sure what happened.
should be fixed now.
