### ISSUE TITLE
GetEVMTransfers API calls obsolete?

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-bootstrap#164]
These API calls seem to be obsolete now:

https://github.com/iotexproject/iotex-bootstrap/blob/master/integration/exchange.md#retrieve-transactions-via-contracts

<img width="905" alt="image" src="https://user-images.githubusercontent.com/11096047/91018234-9cde9a00-e5ef-11ea-8192-ce7fd9174491.png">

**Comment by yutongp** [comment]
We deprecated these two API before we/anyone start using it.
currently, https://docs.iotex.io/developer/core-api/api.html#gettransactionlogbyactionhash and https://docs.iotex.io/developer/core-api/api.html#gettransactionlogbyblockheight are the supported APIs which cover the same feature
