### ISSUE TITLE
Missing Monitor Configuration Guide

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-bootstrap#165]
A file "../monitoring/readme.md" is referenced in the exchange [integration guide](https://github.com/iotexproject/iotex-bootstrap/blob/master/integration/exchange.md#1-deploy-iotex-full-nodes) **but it's missing**. 

Is it located somewhere else, or it's just yet to be written? @yutongp

**Comment by yutongp** [comment]
you are right, the instruction is missing.
We do have a guide here: https://github.com/iotexproject/iotex-bootstrap/tree/master/infra/monitoring

alternatively, if user use our one line upgrader: https://github.com/iotexproject/iotex-bootstrap#upgrade
it asks if user want to turn on monitor, by default it is off:
```
Do you want to monitor the status of the node [Y/N] (Default: N)?
```

**Comment by simonerom** [comment]
Just found it, thanks! Will add this to the docs 👍
