### ISSUE TITLE
Failed to start server.

### ISSUE THREAD

**Issue by zacker0515** [iotexproject/iotex-bootstrap#179]
I follow the step to run iotex node ,but when i run the command :
docker run -d --restart on-failure --name iotex         -p 4689:4689         -p 8080:8080         -v=$IOTEX_HOME/data:/var/data:rw         -v=$IOTEX_HOME/log:/var/log:rw         -v=$IOTEX_HOME/etc/config.yaml:/etc/iotex/config_override.yaml:ro         -v=$IOTEX_HOME/etc/genesis.yaml:/etc/iotex/genesis.yaml:ro         iotex/iotex-core:v1.2.0         iotex-server         -config-path=/etc/iotex/config_override.yaml         -genesis-path=/etc/iotex/genesis.yaml

the error occurd:

{"level":"fatal","ts":1621306827.6981044,"caller":"itx/server.go:174","msg":"Failed to start server.","ioAddr":"io1hrj20xkqd38e8mwjs0af5c4xds0u792land67q","error":"error when starting blockchain: error when starting election committee: failed to get tip height: failed to get tip height: failed to execute callback with any client: 401 Unauthorized account disabled\n","errorVerbose":"401 Unauthorized account disabled\n\nfailed to execute callback with any client\ngithub.com/iotexproject/iotex-election/carrier.(*EthClientPool).Execute\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:111\ngithub.com/iotexproject/iotex-election/carrier.(*ethereumCarrier).tip\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:188\ngithub.com/iotexproject/iotex-election/carrier.(*ethereumCarrier).Tip\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:184\ngithub.com/iotexproject/iotex-election/committee.(*committee).Start\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/committee/committee.go:215\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:471\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:94\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:125\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nfailed to get tip height\ngithub.com/iotexproject/iotex-election/carrier.(*ethereumCarrier).tip\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:203\ngithub.com/iotexproject/iotex-election/carrier.(*ethereumCarrier).Tip\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/carrier/carrier.go:184\ngithub.com/iotexproject/iotex-election/committee.(*committee).Start\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/committee/committee.go:215\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:471\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:94\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:125\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nfailed to get tip height\ngithub.com/iotexproject/iotex-election/committee.(*committee).Start\n\t/go/pkg/mod/github.com/iotexproject/iotex-election@v0.3.5-0.20201031050050-c3ab4f339a54/committee/committee.go:217\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:471\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:94\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:125\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nerror when starting election committee\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:472\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:94\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:125\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:95\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:173\nmain.main\n\t/go/apps/iotex-core/server/main.go:125\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}

please help me

**Comment by simonerom** [comment]
Hi Zacker, it says it cannot start the server and it’s not easy to guess the reasoy. As I also see a “failed to get the tip height” error, it’s possible you have connection issues with your system. I would check:

- the system is connected to the internet
- the node required ports are open in your firewall 
- the node config file is correctly set up

**Comment by zacker0515** [comment]
this config is useful for me:
https://github.com/iotexproject/iotex-core/blob/master/config/standalone-config.yaml

but this config the errror is still here:
https://github.com/iotexproject/iotex-bootstrap/blob/master/config_mainnet.yaml

when i try to chagne the chainDBPath into the snapshot path ,the error is :

{"level":"info","ts":1621328570.526056,"caller":"server/main.go:87","msg":"EVM Network ID: 4689","ioAddr":"io1a8hrkkdchum4c3flckfauzpkwwtxzzfejsdyay"}
{"level":"info","ts":1621328570.52728,"caller":"server/main.go:88","msg":"Genesis timestamp: 1546329600","ioAddr":"io1a8hrkkdchum4c3flckfauzpkwwtxzzfejsdyay"}
{"level":"info","ts":1621328570.5285013,"caller":"server/main.go:89","msg":"Genesis hash: 3dfcdee76186b59a9f9abd0ded8e6c093c35bddea23834044550fb68626adb62","ioAddr":"io1a8hrkkdchum4c3flckfauzpkwwtxzzfejsdyay"}
{"level":"info","ts":1621328570.529858,"caller":"p2p/agent.go:92","msg":"p2p agent","ioAddr":"io1a8hrkkdchum4c3flckfauzpkwwtxzzfejsdyay","topicSuffix":"34044550fb68626adb62"}
{"level":"info","ts":1621328570.531374,"caller":"blockchain/blockchain.go:418","msg":"Add a subscriber.","ioAddr":"io1a8hrkkdchum4c3flckfauzpkwwtxzzfejsdyay"}
{"level":"fatal","ts":1621328570.540341,"caller":"itx/server.go:174","msg":"Failed to start server.","ioAddr":"io1a8hrkkdchum4c3flckfauzpkwwtxzzfejsdyay","error":"error when starting blockchain: error when starting blockchain: feature not supported","errorVerbose":"feature not supported\ngithub.com/iotexproject/iotex-core/blockchain/filedao.init\n\t/data/.iotex/iotex-core/blockchain/filedao/filedao.go:42\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5625\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5620\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5620\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5620\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5620\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5620\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:191\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/data/.iotex/iotex-core/chainservice/chainservice.go:486\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/data/.iotex/iotex-core/server/itx/server.go:94\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/data/.iotex/iotex-core/server/itx/server.go:173\nmain.main\n\t/data/.iotex/iotex-core/server/main.go:125\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/data/.iotex/iotex-core/server/itx/server.go:95\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/data/.iotex/iotex-core/server/itx/server.go:173\nmain.main\n\t/data/.iotex/iotex-core/server/main.go:125\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"}
root@WALLET6:/data/iotex# 

how can i use the snapshot correctly?
 
by the way ,the docker is still abort the same error for me

**Comment by simonerom** [comment]
The config_mainnet is the file you need for your node to join the IoTeX network, as well as you should have downloaded the dab file for mainnet as explained in the Readme.

Please just run the node and ignore initila errors as those could be due to the node not being connected to other p2p peers yet. Once the p2p connection is up the node should start syncing: look for "new block commited" info type of messages and wait for the node to sync up to the tip.

You can install ioctl and point it to your local node (`ioctl config set endpoint localhost:14014 --insecure`) and check the current height with `ioctl bc info`

**Comment by raullenchai** [comment]
@zacker0515 I am going to close this issue and feel free to jump into our discord to get help in real-time - https://discord.gg/Qe6zXCbn
