### ISSUE TITLE
Retry upon 404 and exit if always 404

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-bootstrap#207]
https://github.com/iotexproject/iotex-bootstrap/blob/master/scripts/setup_fullnode.sh#L127

if github is not available, or this file is not available for some reason, the node will have an invalid config.yaml (which prevents the node from up and running). This is a silent fail, which is risky.

The expected behavior:
1. retry upon 404
2. after 10 retries, if one still cannot download all three files, warn the user and quit without doing anything.

**Comment by imakowski** [comment]
Merged
