### ISSUE TITLE
iotex-bootstrap testnet information is invalid

### ISSUE THREAD

**Issue by jrynkiew** [iotexproject/iotex-bootstrap#211]
Currently if someone wanted to start testing on an IoTeX test node, they would fail, as the instructions tell you to use iotex-core 1.6, but the only way to make it work is to use image iotex/iotex-core:v1.6.1-rc2

Please update README.md with current instructions

**Comment by imakowski** [comment]
@raullenchai why not 1.8.2?

**Comment by raullenchai** [comment]
> 

should be 1.8.2 now. This issue has been filed almost 10mo ago

**Comment by imakowski** [comment]
@raullenchai I think this should be closed because README.md is updated already
