### ISSUE TITLE
Fix TestNet indexed data link

### ISSUE THREAD

**Issue by jrynkiew** [iotexproject/iotex-bootstrap#219]
In this section of the docs: 

https://github.com/iotexproject/iotex-bootstrap#join-testnet

There is a link to https://t.iotex.me/testnet-data-with-idx-latest - the testnet indexed data. This link does not work as it should - instead of indexed data it just downloads the regular data.

Please fix. Thanks!

**Comment by Liuhaai** [comment]
thx for feedback

**Comment by xianhuawei** [comment]
![image](https://user-images.githubusercontent.com/3870801/153331048-d1f2d8d1-668c-4b34-929c-de3e7eee847d.png)

fix

**Comment by jrynkiew** [comment]
This is still not fixed. Just tested today, and it still downloads the unindexed data. Please correct it.

![image](https://user-images.githubusercontent.com/63042547/153658737-ba1a77ce-1966-43be-a342-52e4763cb7fc.png)

**Comment by xianhuawei** [comment]
![image](https://user-images.githubusercontent.com/3870801/153784958-6d7c0050-d8aa-4272-90b7-95f2d308ffe5.png)
now redirects to the testnet-data-with-idx-latest.tar.gz
