### ISSUE TITLE
ipfs chainID separation

### ISSUE THREAD

**Issue by jrynkiew** [iotexproject/iotex-bootstrap#224]
With the new 1.7.0 release it was announced that the chain ID's will now properly separate the testnet and Mainnet, however in the config files there are still numerous mentions of the 4689 chain ID (mainnet) on testnet configs. For example here:

https://github.com/iotexproject/iotex-bootstrap/blob/db42b4645e31f08d34bc6e0e9bc6d7fda7028332/config_testnet.yaml#L5

Can this be changed to 4690?

**Comment by imakowski** [comment]
@raullenchai Can I change it to 4690?

**Comment by dustinxie** [comment]
@jrynkiew thanks for checking, here 4689 means the TCP port number used by underlying p2p network communication. so no need to change it
